# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instagarm_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
