# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180408_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagarm_login',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 8, 9, 10, 2, 738679), null=True),
        ),
    ]
