# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180408_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram_follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_follower', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='instagarm_login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
