# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180408_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('unfollow', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.instagarm_login')),
            ],
        ),
    ]
