# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='name_user',
        ),
    ]
